import type { NotificationTemplate } from '@/types/admin-intelligence.types'

/**
 * RentEase notification template library — Flipkart/Amazon style.
 *
 * Three groups:
 *  - occasion  : festival & national-day campaigns (New Year … Big Billion Days)
 *  - category  : product-category offers (Furniture, Gardening, Electronics…)
 *  - lifecycle : transactional/personalized (welcome, cart, booking, delivery…)
 *
 * `templateType` drives backend personalization:
 *  - "welcome" / "cart"      → per-user rendering ({{firstName}}, cart items)
 *  - others                  → static {{variables}} replaced at send time
 */

const OCCASION_THEMES = {
  diwali: { from: '#f59e0b', to: '#b45309', badge: '#fff7ed' },
  holi: { from: '#ec4899', to: '#8b5cf6', badge: '#fdf2f8' },
  christmas: { from: '#dc2626', to: '#047857', badge: '#fef2f2' },
  newYear: { from: '#6366f1', to: '#1e1b4b', badge: '#eef2ff' },
  india: { from: '#ff9933', to: '#138808', badge: '#ffedd5' },
  pink: { from: '#db2777', to: '#9d174d', badge: '#fdf2f8' },
  purple: { from: '#7c3aed', to: '#4c1d95', badge: '#f5f3ff' },
  blue: { from: '#2563eb', to: '#1e3a8a', badge: '#eff6ff' },
  teal: { from: '#0d9488', to: '#134e4a', badge: '#f0fdfa' },
  amber: { from: '#d97706', to: '#78350f', badge: '#fffbeb' },
  rose: { from: '#e11d48', to: '#881337', badge: '#fff1f2' },
  gold: { from: '#ca8a04', to: '#713f12', badge: '#fefce8' },
} as const

const OCCASION_EMOJI: Record<string, string> = {
  'new-year': '🎉',
  'republic-day': '🇮🇳',
  valentine: '💝',
  holi: '🎨',
  'ramzan-eid': '🌙',
  'ram-navami': '🪔',
  'rath-yatra': '🛕',
  'independence-day': '🇮🇳',
  'raksha-bandhan': '🎀',
  janmashtami: '🦚',
  'durga-puja': '🪷',
  diwali: '🪔',
  'bhai-dooj': '🤝',
  christmas: '🎄',
  'big-billion-days': '💥',
  'year-end-sale': '🌟',
}

const t = (partial: Partial<NotificationTemplate> & Pick<NotificationTemplate, '_id' | 'name' | 'slug' | 'subject' | 'message' | 'category' | 'channels'>): NotificationTemplate => ({
  variables: [],
  usageCount: 0,
  isActive: true,
  createdAt: '2026-01-01T00:00:00Z',
  updatedAt: '2026-01-01T00:00:00Z',
  ...partial,
})

export const OCCASION_TEMPLATES: NotificationTemplate[] = [
  t({
    _id: 'tpl-new-year',
    name: 'New Year Sale',
    slug: 'new-year-sale',
    subject: '🎉 New Year, New Home! Up to {{discount}}% off',
    message: 'Start the year fresh — rent sofas, beds & decor at up to {{discount}}% off. Limited time!',
    category: 'promotional',
    channels: ['push', 'in_app', 'email', 'sms'],
    variables: ['discount', 'endTime'],
    group: 'occasion',
    templateType: 'promotion',
    defaultVariables: { discount: '30', endTime: 'tonight' },
    defaultActionUrl: '/products',
    theme: OCCASION_THEMES.newYear,
  }),
  t({
    _id: 'tpl-republic-day',
    name: 'Republic Day Sale',
    slug: 'republic-day-sale',
    subject: '🇮🇳 Republic Day Sale — {{discount}}% off storewide',
    message: 'Celebrate the spirit of India with {{discount}}% off on every rental. Sale ends {{endTime}}!',
    category: 'promotional',
    channels: ['push', 'in_app', 'email'],
    variables: ['discount', 'endTime'],
    group: 'occasion',
    templateType: 'promotion',
    defaultVariables: { discount: '25', endTime: 'Jan 26' },
    defaultActionUrl: '/products',
    theme: OCCASION_THEMES.india,
  }),
  t({
    _id: 'tpl-valentine',
    name: "Valentine's Day",
    slug: 'valentine-day',
    subject: '💝 Surprise your loved one with a cosy rental',
    message: 'This Valentine’s, gift an experience — cosy sofas, dream beds & romantic decor at {{discount}}% off.',
    category: 'promotional',
    channels: ['push', 'in_app', 'email'],
    variables: ['discount'],
    group: 'occasion',
    templateType: 'promotion',
    defaultVariables: { discount: '20' },
    defaultActionUrl: '/products',
    theme: OCCASION_THEMES.pink,
  }),
  t({
    _id: 'tpl-holi',
    name: 'Holi Sale',
    slug: 'holi-sale',
    subject: '🎨 Holi Hai! {{discount}}% off on colourful home decor',
    message: 'Add colour to your home this Holi — decor, carpets & furniture at {{discount}}% off. Hurry!',
    category: 'promotional',
    channels: ['push', 'in_app', 'email', 'sms'],
    variables: ['discount'],
    group: 'occasion',
    templateType: 'promotion',
    defaultVariables: { discount: '25' },
    defaultActionUrl: '/products',
    theme: OCCASION_THEMES.holi,
  }),
  t({
    _id: 'tpl-ramzan-eid',
    name: 'Ramzan Eid Sale',
    slug: 'ramzan-eid',
    subject: '🌙 Eid Mubarak! Festive deals up to {{discount}}% off',
    message: 'Eid Mubarak! Celebrate with family — furniture & decor at up to {{discount}}% off this festive week.',
    category: 'promotional',
    channels: ['push', 'in_app', 'email'],
    variables: ['discount'],
    group: 'occasion',
    templateType: 'promotion',
    defaultVariables: { discount: '30' },
    defaultActionUrl: '/products',
    theme: OCCASION_THEMES.gold,
  }),
  t({
    _id: 'tpl-ram-navami',
    name: 'Ram Navami',
    slug: 'ram-navami',
    subject: '🪔 Ram Navami wishes — special rental offers live',
    message: 'On this auspicious Ram Navami, bring home comfort — exclusive {{discount}}% off on select furniture.',
    category: 'promotional',
    channels: ['push', 'in_app'],
    variables: ['discount'],
    group: 'occasion',
    templateType: 'promotion',
    defaultVariables: { discount: '15' },
    defaultActionUrl: '/products',
    theme: OCCASION_THEMES.amber,
  }),
  t({
    _id: 'tpl-rath-yatra',
    name: 'Rath Yatra Sale',
    slug: 'rath-yatra',
    subject: '🛕 Rath Yatra sale is live — grab {{discount}}% off',
    message: 'The Rath Yatra sale has arrived! Up to {{discount}}% off on home essentials & furniture.',
    category: 'promotional',
    channels: ['push', 'in_app', 'email'],
    variables: ['discount'],
    group: 'occasion',
    templateType: 'promotion',
    defaultVariables: { discount: '20' },
    defaultActionUrl: '/products',
    theme: OCCASION_THEMES.amber,
  }),
  t({
    _id: 'tpl-independence-day',
    name: 'Independence Day',
    slug: 'independence-day',
    subject: '🇮🇳 Freedom Sale — {{discount}}% off storewide',
    message: 'Celebrate freedom with {{discount}}% off on every rental. Be proud, be comfortable!',
    category: 'promotional',
    channels: ['push', 'in_app', 'email', 'sms'],
    variables: ['discount'],
    group: 'occasion',
    templateType: 'promotion',
    defaultVariables: { discount: '20' },
    defaultActionUrl: '/products',
    theme: OCCASION_THEMES.india,
  }),
  t({
    _id: 'tpl-raksha-bandhan',
    name: 'Raksha Bandhan',
    slug: 'raksha-bandhan',
    subject: '🎀 Rakhi special: gifts that last all year',
    message: 'This Raksha Bandhan, gift your sibling something they’ll love every day — rentals at {{discount}}% off.',
    category: 'promotional',
    channels: ['push', 'in_app', 'email'],
    variables: ['discount'],
    group: 'occasion',
    templateType: 'promotion',
    defaultVariables: { discount: '18' },
    defaultActionUrl: '/products',
    theme: OCCASION_THEMES.pink,
  }),
  t({
    _id: 'tpl-janmashtami',
    name: 'Janmashtami',
    slug: 'janmashtami',
    subject: '🦚 Happy Janmashtami! Festive offers live now',
    message: 'Happy Janmashtami! Celebrate with {{discount}}% off on furniture & festive decor.',
    category: 'promotional',
    channels: ['push', 'in_app'],
    variables: ['discount'],
    group: 'occasion',
    templateType: 'promotion',
    defaultVariables: { discount: '15' },
    defaultActionUrl: '/products',
    theme: OCCASION_THEMES.teal,
  }),
  t({
    _id: 'tpl-durga-puja',
    name: 'Durga Puja',
    slug: 'durga-puja',
    subject: '🪷 Shubho Durga Puja! {{discount}}% off festive essentials',
    message: 'Shubho Durga Puja! Bring the pandal home — decor & furniture at {{discount}}% off.',
    category: 'promotional',
    channels: ['push', 'in_app', 'email'],
    variables: ['discount'],
    group: 'occasion',
    templateType: 'promotion',
    defaultVariables: { discount: '25' },
    defaultActionUrl: '/products',
    theme: OCCASION_THEMES.rose,
  }),
  t({
    _id: 'tpl-diwali',
    name: 'Diwali Dhamaka',
    slug: 'diwali-dhamaka',
    subject: '🪔 Diwali Dhamaka! Up to {{discount}}% off — light up your home',
    message: 'This Diwali, light up every corner — furniture, decor & appliances at up to {{discount}}% off!',
    category: 'promotional',
    channels: ['push', 'in_app', 'email', 'sms'],
    variables: ['discount', 'endTime'],
    group: 'occasion',
    templateType: 'promotion',
    defaultVariables: { discount: '40', endTime: 'Diwali night' },
    defaultActionUrl: '/products',
    theme: OCCASION_THEMES.diwali,
  }),
  t({
    _id: 'tpl-bhai-dooj',
    name: 'Bhai Dooj',
    slug: 'bhai-dooj',
    subject: '🤝 Bhai Dooj: gifts that last longer',
    message: 'This Bhai Dooj, gift comfort — {{discount}}% off on furniture & home essentials.',
    category: 'promotional',
    channels: ['push', 'in_app'],
    variables: ['discount'],
    group: 'occasion',
    templateType: 'promotion',
    defaultVariables: { discount: '15' },
    defaultActionUrl: '/products',
    theme: OCCASION_THEMES.gold,
  }),
  t({
    _id: 'tpl-christmas',
    name: 'Christmas Sale',
    slug: 'christmas-sale',
    subject: '🎄 Merry Christmas! {{discount}}% off home & decor',
    message: 'Deck your home this Christmas — furniture & decor at {{discount}}% off. Joy to the world!',
    category: 'promotional',
    channels: ['push', 'in_app', 'email', 'sms'],
    variables: ['discount'],
    group: 'occasion',
    templateType: 'promotion',
    defaultVariables: { discount: '35' },
    defaultActionUrl: '/products',
    theme: OCCASION_THEMES.christmas,
  }),
  t({
    _id: 'tpl-big-billion-days',
    name: 'Big Billion Days',
    slug: 'big-billion-days',
    subject: '💥 Big Billion Days are here — up to {{discount}}% off',
    message: 'The biggest sale of the year! Up to {{discount}}% off on everything. Limited stock, act fast.',
    category: 'promotional',
    channels: ['push', 'in_app', 'email', 'sms'],
    variables: ['discount', 'endTime'],
    group: 'occasion',
    templateType: 'promotion',
    defaultVariables: { discount: '50', endTime: 'midnight' },
    defaultActionUrl: '/products',
    theme: OCCASION_THEMES.blue,
  }),
  t({
    _id: 'tpl-year-end',
    name: 'Year-End Sale',
    slug: 'year-end-sale',
    subject: '🌟 Year-End Sale: clear the old, rent the new',
    message: 'End the year on a high note — {{discount}}% off storewide on all rentals!',
    category: 'promotional',
    channels: ['push', 'in_app', 'email'],
    variables: ['discount'],
    group: 'occasion',
    templateType: 'promotion',
    defaultVariables: { discount: '25' },
    defaultActionUrl: '/products',
    theme: OCCASION_THEMES.newYear,
  }),
]

export const CATEGORY_TEMPLATES: NotificationTemplate[] = [
  t({
    _id: 'tpl-furniture',
    name: 'Furniture Sale',
    slug: 'furniture-sale',
    subject: '🛋️ Furniture {{discount}}% off — Sofas, Beds & more',
    message: 'Upgrade your space — sofas, beds, wardrobes & more at {{discount}}% off. Only this week!',
    category: 'promotional',
    channels: ['push', 'in_app', 'email'],
    variables: ['discount', 'endTime'],
    group: 'category',
    templateType: 'promotion',
    defaultVariables: { discount: '20', endTime: 'this Sunday' },
    defaultActionUrl: '/products?category=furniture',
    theme: OCCASION_THEMES.amber,
  }),
  t({
    _id: 'tpl-gardening',
    name: 'Gardening Tools',
    slug: 'gardening-tools',
    subject: '🪴 Gardening tools {{discount}}% off — grow your green space',
    message: 'Green fingers, happy home! Gardening essentials at {{discount}}% off.',
    category: 'promotional',
    channels: ['push', 'in_app'],
    variables: ['discount'],
    group: 'category',
    templateType: 'promotion',
    defaultVariables: { discount: '20' },
    defaultActionUrl: '/products?category=gardening',
    theme: OCCASION_THEMES.teal,
  }),
  t({
    _id: 'tpl-electronics',
    name: 'Electronics',
    slug: 'electronics-sale',
    subject: '📺 Electronics {{discount}}% off — TVs, ACs, Fridges',
    message: 'Upgrade your entertainment — TVs, ACs & appliances at {{discount}}% off.',
    category: 'promotional',
    channels: ['push', 'in_app', 'email'],
    variables: ['discount'],
    group: 'category',
    templateType: 'promotion',
    defaultVariables: { discount: '18' },
    defaultActionUrl: '/products?category=electronics',
    theme: OCCASION_THEMES.blue,
  }),
  t({
    _id: 'tpl-home-decor',
    name: 'Home Decor',
    slug: 'home-decor-sale',
    subject: '🖼️ Home decor {{discount}}% off — make it yours',
    message: 'Small changes, big impact — lamps, rugs, art & more at {{discount}}% off.',
    category: 'promotional',
    channels: ['push', 'in_app'],
    variables: ['discount'],
    group: 'category',
    templateType: 'promotion',
    defaultVariables: { discount: '22' },
    defaultActionUrl: '/products?category=home-decor',
    theme: OCCASION_THEMES.purple,
  }),
  t({
    _id: 'tpl-appliances',
    name: 'Appliances',
    slug: 'appliances-sale',
    subject: '🧺 Appliances {{discount}}% off — washers, microwaves & more',
    message: 'Make life easier — home appliances at {{discount}}% off this week.',
    category: 'promotional',
    channels: ['push', 'in_app', 'email'],
    variables: ['discount'],
    group: 'category',
    templateType: 'promotion',
    defaultVariables: { discount: '15' },
    defaultActionUrl: '/products?category=appliances',
    theme: OCCASION_THEMES.rose,
  }),
  t({
    _id: 'tpl-kitchen',
    name: 'Kitchen Essentials',
    slug: 'kitchen-essentials',
    subject: '🍳 Kitchen essentials {{discount}}% off',
    message: 'Cook with joy — kitchen & dining essentials at {{discount}}% off.',
    category: 'promotional',
    channels: ['push', 'in_app'],
    variables: ['discount'],
    group: 'category',
    templateType: 'promotion',
    defaultVariables: { discount: '20' },
    defaultActionUrl: '/products?category=kitchen',
    theme: OCCASION_THEMES.gold,
  }),
]

export const LIFECYCLE_TEMPLATES: NotificationTemplate[] = [
  t({
    _id: 'tpl-welcome',
    name: 'Welcome to RentEase',
    slug: 'welcome-rentease',
    subject: 'Hi {{firstName}}, welcome to RentEase! 🎉',
    message: 'Welcome aboard, {{firstName}}! Discover premium furniture & appliances on rent — flexible plans, zero hassle.',
    category: 'lifecycle',
    channels: ['push', 'in_app', 'email'],
    variables: ['firstName', 'name'],
    group: 'lifecycle',
    templateType: 'welcome',
    defaultActionUrl: '/products',
    theme: OCCASION_THEMES.blue,
  }),
  t({
    _id: 'tpl-cart',
    name: 'Cart Abandoned',
    slug: 'cart-abandoned',
    subject: 'Your cart is waiting, {{firstName}}',
    message: 'You left {{cartCount}} item(s) in your cart — {{cartItems}}. Complete your rental before it expires!',
    category: 'reminders',
    channels: ['push', 'in_app', 'email', 'sms'],
    variables: ['firstName', 'cartCount', 'cartItems'],
    group: 'lifecycle',
    templateType: 'cart',
    withCart: true,
    defaultActionUrl: '/cart',
    theme: OCCASION_THEMES.amber,
  }),
  t({
    _id: 'tpl-booking',
    name: 'Booking Confirmed',
    slug: 'booking-confirmed',
    subject: 'Booking #{{bookingId}} confirmed, {{firstName}}!',
    message: 'Great news! Your rental #{{bookingId}} is confirmed. Expected delivery: {{deliveryDate}}.',
    category: 'transactional',
    channels: ['push', 'in_app', 'email', 'sms'],
    variables: ['bookingId', 'firstName', 'deliveryDate'],
    group: 'lifecycle',
    templateType: 'booking',
    defaultActionUrl: '/orders',
    theme: OCCASION_THEMES.teal,
  }),
  t({
    _id: 'tpl-delivery',
    name: 'Delivery Update',
    slug: 'delivery-update',
    subject: 'Your order is out for delivery, {{firstName}} 📦',
    message: 'Track your delivery in real-time — your items arrive soon! Tracking: {{trackingId}}.',
    category: 'transactional',
    channels: ['push', 'in_app', 'sms'],
    variables: ['firstName', 'trackingId'],
    group: 'lifecycle',
    templateType: 'delivery',
    defaultActionUrl: '/orders',
    theme: OCCASION_THEMES.purple,
  }),
  t({
    _id: 'tpl-rental-reminder',
    name: 'Rental Return Reminder',
    slug: 'rental-return-reminder',
    subject: 'Hi {{firstName}}, your rental returns on {{returnDate}}',
    message: 'Rental #{{rentalNumber}} is due for return on {{returnDate}}. Need to extend? Just tap below.',
    category: 'reminders',
    channels: ['push', 'in_app', 'sms'],
    variables: ['firstName', 'rentalNumber', 'returnDate'],
    group: 'lifecycle',
    templateType: 'reminder',
    defaultActionUrl: '/orders',
    theme: OCCASION_THEMES.rose,
  }),
]

export const NOTIFICATION_TEMPLATES: NotificationTemplate[] = [
  ...OCCASION_TEMPLATES,
  ...CATEGORY_TEMPLATES,
  ...LIFECYCLE_TEMPLATES,
]

export const TEMPLATE_GROUPS: { value: string; label: string; emoji: string }[] = [
  { value: 'occasion', label: 'Occasions & Festivals', emoji: '🎊' },
  { value: 'category', label: 'Category Offers', emoji: '🏷️' },
  { value: 'lifecycle', label: 'Lifecycle & Alerts', emoji: '🔔' },
]

export function getTemplateEmoji(slug: string): string {
  return OCCASION_EMOJI[slug] ?? '📣'
}

export function getGroupLabel(group?: string): string {
  return TEMPLATE_GROUPS.find((g) => g.value === group)?.label ?? 'Template'
}
