import { motion } from 'framer-motion'
import { Sparkles, Clock, Bot } from 'lucide-react'
import { ConfidenceBar } from './ConfidenceBar'
import { avgConfidence, type DerivedInsight } from './ai-insights.utils'

interface ExecutiveSummaryProps {
  summary: string
  insights: DerivedInsight[]
  timestamp?: string
}

export function ExecutiveSummary({ summary, insights, timestamp }: ExecutiveSummaryProps) {
  const confidence = avgConfidence(insights)
  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      className="relative overflow-hidden rounded-3xl border border-indigo-100 bg-gradient-to-br from-indigo-600 via-violet-600 to-blue-600 p-6 text-white shadow-lg"
    >
      <div className="pointer-events-none absolute -right-16 -top-16 h-56 w-56 rounded-full bg-white/10 blur-2xl" />
      <div className="relative flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between">
        <div className="max-w-2xl">
          <div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-indigo-100">
            <Sparkles className="h-3.5 w-3.5 text-amber-300" />
            Executive Summary
          </div>
          <p className="text-lg font-semibold leading-snug">{summary}</p>
          <div className="mt-3 flex flex-wrap items-center gap-4 text-xs text-indigo-100">
            <span className="inline-flex items-center gap-1.5">
              <Bot className="h-3.5 w-3.5" /> Generated by AI Engine
            </span>
            {timestamp && (
              <span className="inline-flex items-center gap-1.5">
                <Clock className="h-3.5 w-3.5" /> {timestamp}
              </span>
            )}
            <span className="inline-flex items-center gap-1.5">
              {insights.length} insights
            </span>
          </div>
        </div>
        <div className="w-full max-w-xs shrink-0 rounded-2xl bg-white/10 p-4 backdrop-blur">
          <ConfidenceBar value={confidence} label="Avg. confidence" light />
        </div>
      </div>
    </motion.div>
  )
}

export default ExecutiveSummary
